name: Daily Job

on:
  schedule:
    - cron: '*/5 * * * *'  # This runs at 00:00 UTC every day

jobs:
  run_daily_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run your script
        run: |
          echo "test"
        # cd datacake_newsletter
        # crewai run
